/* -- CARGA INICIAL DE DATOS, ESTOS SON LOS DATOS BASE QUE SE UTILIZARÁN EN TODO EL SISTEMA, A LAS TABLAS QUE NO SE LES AGREGÓ NADA EN ESTE PROCESO FUE PORQUE SON LAS TABLAS QUE SE LLENARÁN DURANTE LA EJECUCIÓN Y CONFIGURACIÓN DEL SISTEMA

-- SE INSERTAN LOS TIPOS DE ELECCIONES BASE
INSERT INTO TiposEleccion (IdTipoEleccion, Descripcion)
VALUES(1, 'Presidencial'), (2, 'Diputación')

-- SE INSERTAN LOS ESTADOS BASE
INSERT INTO Estados(IdEstado, Descripcion)
VALUES (1, 'Eliminado'), (2, 'Activo')

-- SE INSERTAN LOS PERFILES BASE
INSERT INTO Perfiles (Descripcion)
VALUES ('Administrador'), ('Votante')

-- SE INSERTAN LAS PROVINCIAS APARTIR DEL DISTRITO_ELECTORAL
INSERT INTO Provincias (CodigoProvincia, Descripcion)
SELECT CodigoProvincia, Provincia 
FROM [dbo].[DISTRITOS_ELECTORALES_SEPARADA]
GROUP BY CodigoProvincia, Provincia 

-- SE INSERTAN LOS CANTONES APARTIR DEL DISTRITO_ELECTORAL
INSERT INTO Cantones(CodigoProvincia, CodigoCanton, Descripcion)
SELECT CodigoProvincia, CodigoCanton, Canton 
FROM [dbo].[DISTRITOS_ELECTORALES_SEPARADA]
GROUP BY CodigoProvincia, CodigoCanton, Canton 

-- SE INSERTAN LOS DISTRITOS APARTIR DEL DISTRITO_ELECTORAL
INSERT INTO Distritos(CodigoProvincia, CodigoCanton, CodigoDistrito, Descripcion)
SELECT CodigoProvincia, CodigoCanton, CodigoDistrito, Distrito 
FROM [dbo].[DISTRITOS_ELECTORALES_SEPARADA]
GROUP BY CodigoProvincia, CodigoCanton, CodigoDistrito, Distrito

-- SE INSERTAN LA CANTIDAD DE DIPUTADOS QUE PUEDE OBTENER CADA PARTIDO POR PROVINCIA
INSERT INTO Diputados_x_Provincia (CodigoProvincia, Cantidad)
VALUES ('1', 18),('2', 12),('3', 6),('4', 5),('5', 5),('6', 6),('7', 5)

-- SE INSERTA EL DISTRITOELECTORAL APARTIR DE OTRA TABLA DE DISTRITOELECTORAL QUE SUFRIÓ CAMBIOS
INSERT INTO [dbo].[DistritosElectorales] (Codele, CodigoProvincia, CodigoCanton, CodigoDistrito)
SELECT CODELE, CodigoProvincia, CodigoCanton, CodigoDistrito
FROM [dbo].[DISTRITOS_ELECTORALES_SEPARADA]

-- SE INSERTA EL PADRONNACIONAL APARTIR DE LA TABLA INICIAL DE PADRONNACIONAL
INSERT INTO [PadronNacional] (Cedula, Codele, Sexo, FechaVencimientoCedula, NumeroJuntaReceptora, Nombre, PrimerApellido, SegundoApellido)
SELECT Cedula, CODELEC, '' AS SEXO, FECHACADUC, JUNTA, Nombre, PRIMER_APELLIDO, SEGUNDO_APELLIDO
FROM [dbo].[PADRON_COMPLETO]
*/

-- LIMPIEZA DE ESPACIOS VACIOS A LA DERECHA Y/O IZQUIERDA EN LOS CAMPOS DE PROVINCIA, CANTON, DISTRITO
SELECT *
-- UPDATE A SET PROVINCIA = TRIM(PROVINCIA), CANTON = TRIM(CANTON), DISTRITO = TRIM(DISTRITO)
FROM [dbo].[DISTRITOS_ELECTORALES_COMPLETO] A

/*
-- INSERTAR EN LA TABLA DE DISTRITOS ELECTORALES CON LOS CAMPOS DE CÓDIGO PROVINCIA, CANTÓN Y DISTRITO. SE MANTIENE LA COLUMNA DE CODELE Y LA DESCRIPCIÓN DE CADA PROVINCIA, CANTÓN Y DISTRITO
-- INSERT INTO DISTRITOS_ELECTORALES
SELECT CODELE, LEFT(CODELE, 1) AS CodigoProvincia, PROVINCIA, SUBSTRING(CODELE, 2, 2) AS CodigoCanton, Canton, RIGHT(CODELE, 3) as CodigoDistrito, DISTRITO
FROM [dbo].[DISTRITOS_ELECTORALES_COMPLETO] A
*/

/*
-- INSERTAR PROVINCIAS A PARTIR DE LA TABLA DE DISTRITOS ELECTORALES
INSERT INTO PROVINCIAS
SELECT LEFT(CODELE, 1) AS Codigo, PROVINCIA
FROM [dbo].[DISTRITOS_ELECTORALES] A
GROUP BY LEFT(CODELE, 1), PROVINCIA
*/

/*
-- INSERTAR CANTONES A PARTIR DE LA TABLA DE DISTRITOS ELECTORALES
-- INSERT INTO CANTONES
SELECT LEFT(CODELE, 1) AS CodigoProvincia, SUBSTRING(CODELE, 2, 2) AS CodigoCanton, CANTON
FROM [dbo].[DISTRITOS_ELECTORALES] A
GROUP BY LEFT(CODELE, 1), SUBSTRING(CODELE, 2, 2),CANTON
*/

/*
-- INSERTAR DISTRITOS A PARTIR DE LA TABLA DE DISTRITOS ELECTORALES
-- INSERT INTO DISTRITOS
-- UPDATE A SET PROVINCIA = TRIM(PROVINCIA), CANTON = TRIM(CANTON), DISTRITO = TRIM(DISTRITO)
FROM [dbo].[DISTRITOS_ELECTORALES] A
GROUP BY LEFT(CODELE, 1), SUBSTRING(CODELE, 2, 2), RIGHT(CODELE, 3), DISTRITO
*/