-- LA CARGA TOTAL SE HACE POR MEDIO DEL AGENTE DEL SQL SERVER
-- AQUÍ SE FORMATEA LA COLUMNA DE FECHACADUC PARA QUE SEA REALMENTE DE TIPO FECHA Y A LOS APELLIDOS Y NOMBRE SE LES QUITAN LOS ESPACIOS A LA DERECHA
SELECT CEDULA, CODELEC, RELLENO, CONVERT(DATE, FECHACADUC) AS FECHACADUC, JUNTA, 
TRIM(NOMBRE) AS NOMBRE, TRIM(PRIMER_APELLIDO) AS PRIMER_APELLIDO, TRIM(SEGUNDO_APELLIDO) AS SEGUNDO_APELLIDO
-- INTO PADRON_COMPLETO
FROM [Sist_Votaciones_Electronicos].[dbo].[PADRON_ELECTORAL]